version: "2.2"
x-global-values:
  teamtalk-image: &teamtalk-image ${TT_IMAGE_PREFIX:-docker.io/rayson/}teamtalk:latest
  teamtalk-admin-image: &teamtalk-admin-image ${TT_IMAGE_PREFIX:-docker.io/rayson/}teamtalk-admin:latest
x-teamtalk-service-template: &teamtalk-service-template
  image: *teamtalk-image
  build:
    context: images/teamtalk
services:
  redis:
    # usage: https://hub.docker.com/r/centos/redis-32-centos7
    image: docker.io/centos/redis-32-centos7:latest
    user: "1001:0"
    environment:
      REDIS_PASSWORD:
    volumes:
    - redis-data:/var/lib/redis/data:rw
    ports:
    - 6379/tcp
  db:
    # usage: https://hub.docker.com/r/centos/mariadb-102-centos7
    image: docker.io/centos/mariadb-102-centos7:latest
    user: "1001:0"
    environment:
      MYSQL_USER: teamtalk
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: teamtalk
    volumes:
    - mysql-data:/var/lib/mysql/data:rw
    - ./db:/vol/db:rw
    ports:
    - 3306/tcp
  db-proxy:
    <<: *teamtalk-service-template
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/db_proxy_server
    command: ./db_proxy_server
    ports:
    - 10600/tcp
    volumes:
    - ./conf/dbproxyserver.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/db_proxy_server/dbproxyserver.conf:ro
  login:
    <<: *teamtalk-service-template
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/login_server
    command: ./login_server
    ports:
    - 8008/tcp # for client
    - 8100/tcp # for msg_server
    - 8080:8080/tcp # for http
    volumes:
    - ./conf/loginserver.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/db_proxy_server/loginserver.conf:ro
  msg:
    <<: *teamtalk-service-template
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/msg_server
    command: ./msg_server
    ports:
    - 8000:8000/tcp
    volumes:
    - ./conf/msgserver.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/msg_server/msgserver.conf:ro
  route:
    <<: *teamtalk-service-template
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/route_server
    command: ./route_server
    ports:
    - 8200/tcp
    volumes:
     - ./conf/routeserver.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/route_server/routeserver.conf:ro
  http-msg:
    <<: *teamtalk-service-template
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/http_msg_server
    command: ./http_msg_server
    ports:
    - 8400:8400/tcp
    volumes:
     - ./conf/httpmsgserver.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/http_msg_server/httpmsgserver.conf:ro
  file:
    <<: *teamtalk-service-template
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/file_server
    command: ./file_server
    ports:
    - 8600:8600/tcp
    - 8601/tcp
    volumes:
     - ./conf/fileserver.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/file_server/fileserver.conf:ro
  msfs:
    <<: *teamtalk-service-template
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/msfs
    command: ./msfs
    ports:
    - 8700:8700/tcp
    volumes:
     - ./conf/msfs.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/msfs/msfs.conf:ro
  push:
    <<: *teamtalk-service-template
    scale: 0 # disabled by default
    working_dir: /root/TeamTalk/auto_setup/im_server/im-server-1.0.0/push_server
    command: ./push_server
    ports:
    - 8500/tcp
    volumes:
     - ./conf/pushserver.conf:/root/TeamTalk/auto_setup/im_server/im-server-1.0.0/push_server/pushserver.conf:ro
  admin:
    image: *teamtalk-admin-image
    build:
      context: images/teamtalk-admin
    ports:
    - 10080:80/tcp
    volumes:
    - ./conf/config.php:/var/www/html/application/config/config.php:ro
    - ./conf/database.php:/var/www/html/application/config/database.php:ro
    - ./conf/im.conf:/etc/httpd/conf.d/im.conf:rw

volumes:
  redis-data:
  mysql-data:
